"""Added relation between attempts and challenges

Revision ID: 3b8c8f79b74a
Revises: ab3e2713831b
Create Date: 2020-09-18 10:49:39.520318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8c8f79b74a'
down_revision = 'ab3e2713831b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_to_challenge_table',
    sa.Column('attempts_id', sa.Integer(), nullable=True),
    sa.Column('challenges_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempts_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['challenges_id'], ['challenges.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_to_challenge_table')
    # ### end Alembic commands ###
