"""Added user_type column to User model

Revision ID: 74e719e9a182
Revises: 6336478c122c
Create Date: 2020-09-16 05:47:31.646929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e719e9a182'
down_revision = '6336478c122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.Enum('ADMIN', 'PLAYER', 'CONTRIBUTOR', name='usertype'), server_default='PLAYER', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
