"""Added relation between a team and player owner

Revision ID: c9c4be32d223
Revises: 581d6085fd92
Create Date: 2020-09-26 11:03:12.436294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c4be32d223'
down_revision = '581d6085fd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('captain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['captain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'captain_id')
    # ### end Alembic commands ###
